# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_search:
    resource: "@LakionSyliusElasticSearchBundle/Resources/config/routing.yml"

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

lakion_elastic_search_shop_product_index:
        path: /products
        methods: [GET]
        defaults:
             _controller: lakion_sylius_elastic_search.controller.search:filterAction
             _sylius:
                template: "@LakionSyliusElasticSearch/Product/index.html.twig"
                resource_class: "%sylius.model.product.class%"
                filter_set: default
        requirements:
            slug: .+

app_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: app.controller.search:searchAction
        _sylius:
            template: "Search/search.html.twig"
            resource_class: "%sylius.model.product.class%"
            filter_set: default
